spring.application.name=demo
spring.data.mongodb.uri=${MONGO_URI}
spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=postgres
spring.datasource.password=${PSQL_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
server.port=8080
spring.servlet.multipart.enabled=true
spring.jpa.show-sql=true
server.connection.timeout=60000
